const translations = {
    'en-US': {
        settings: 'Settings',
        settingsTitle: 'Settings',
        theme: 'Theme:',
        toggleTheme: '',
        language: 'Language:',
        searchSources: 'Search Sources',
        addSource: 'Add New Source',
        editSourceTitle: 'Edit Search Source',
        sourceName: 'Name:',
        sourceUrl: 'URL (use %s for query):',
        sourceFavicon: 'Favicon URL:',
        sourceLogo: 'Text Logo Path (optional):',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        searchPlaceholder: 'Search...',
        defaultSourceName: 'New Search Engine'
    },
    'en-GB': {
        settings: 'Settings',
        settingsTitle: 'Settings',
        theme: 'Theme:',
        toggleTheme: '',
        language: 'Language:',
        searchSources: 'Search Sources',
        addSource: 'Add New Source',
        editSourceTitle: 'Edit Search Source',
        sourceName: 'Name:',
        sourceUrl: 'URL (use %s for query):',
        sourceFavicon: 'Favicon URL:',
        sourceLogo: 'Text Logo Path (optional):',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        searchPlaceholder: 'Search...',
        defaultSourceName: 'New Search Engine'
    },
    'zh-CN': {
        settings: '设置',
        settingsTitle: '设置',
        theme: '主题:',
        toggleTheme: '',
        language: '语言:',
        searchSources: '搜索源',
        addSource: '添加搜索源',
        editSourceTitle: '编辑搜索源',
        sourceName: '名称:',
        sourceUrl: 'URL (使用 %s 作为查询占位符):',
        sourceFavicon: 'Favicon URL:',
        sourceLogo: '文字Logo路径 (可选):',
        save: '保存',
        cancel: '取消',
        delete: '删除',
        edit: '编辑',
        searchPlaceholder: '搜索...',
        defaultSourceName: '新搜索引擎'
    },
    'zh-TW': {
        settings: '設定',
        settingsTitle: '設定',
        theme: '主題:',
        toggleTheme: '',
        language: '語言:',
        searchSources: '搜尋來源',
        addSource: '新增搜尋來源',
        editSourceTitle: '編輯搜尋來源',
        sourceName: '名稱:',
        sourceUrl: 'URL (使用 %s 作為查詢預留位置):',
        sourceFavicon: 'Favicon URL:',
        sourceLogo: '文字Logo路徑 (可選):',
        save: '儲存',
        cancel: '取消',
        delete: '刪除',
        edit: '編輯',
        searchPlaceholder: '搜尋...',
        defaultSourceName: '新搜尋引擎'
    },
    'fr-FR': {
        settings: 'Paramètres',
        settingsTitle: 'Paramètres',
        theme: 'Thème:',
        toggleTheme: '',
        language: 'Langue:',
        searchSources: 'Sources de recherche',
        addSource: 'Ajouter une source',
        editSourceTitle: 'Modifier la source de recherche',
        sourceName: 'Nom:',
        sourceUrl: 'URL (utilisez %s pour la requête):',
        sourceFavicon: 'URL du Favicon:',
        sourceLogo: 'Chemin du logo texte (optionnel):',
        save: 'Enregistrer',
        cancel: 'Annuler',
        delete: 'Supprimer',
        edit: 'Modifier',
        searchPlaceholder: 'Rechercher...',
        defaultSourceName: 'Nouveau moteur de recherche'
    },
    'ru-RU': {
        settings: 'Настройки',
        settingsTitle: 'Настройки',
        theme: 'Тема:',
        toggleTheme: '',
        language: 'Язык:',
        searchSources: 'Источники поиска',
        addSource: 'Добавить источник',
        editSourceTitle: 'Редактировать источник поиска',
        sourceName: 'Имя:',
        sourceUrl: 'URL (используйте %s для запроса):',
        sourceFavicon: 'URL Favicon:',
        sourceLogo: 'Путь к текстовому логотипу (необязательно):',
        save: 'Сохранить',
        cancel: 'Отмена',
        delete: 'Удалить',
        edit: 'Редакт.',
        searchPlaceholder: 'Поиск...',
        defaultSourceName: 'Новая поисковая система'
    },
    'es-ES': {
        settings: 'Ajustes',
        settingsTitle: 'Ajustes',
        theme: 'Tema:',
        toggleTheme: '',
        language: 'Idioma:',
        searchSources: 'Fuentes de búsqueda',
        addSource: 'Añadir fuente',
        editSourceTitle: 'Editar fuente de búsqueda',
        sourceName: 'Nombre:',
        sourceUrl: 'URL (use %s para la consulta):',
        sourceFavicon: 'URL del Favicon:',
        sourceLogo: 'Ruta del logo de texto (opcional):',
        save: 'Guardar',
        cancel: 'Cancelar',
        delete: 'Eliminar',
        edit: 'Editar',
        searchPlaceholder: 'Buscar...',
        defaultSourceName: 'Nuevo motor de búsqueda'
    },
    'ar-SA': {
        settings: 'الإعدادات',
        settingsTitle: 'الإعدادات',
        theme: 'المظهر:',
        toggleTheme: '',
        language: 'اللغة:',
        searchSources: 'مصادر البحث',
        addSource: 'إضافة مصدر',
        editSourceTitle: 'تعديل مصدر البحث',
        sourceName: 'الاسم:',
        sourceUrl: 'الرابط (استخدم %s للاستعلام):',
        sourceFavicon: 'رابط الأيقونة المصغرة:',
        sourceLogo: 'مسار شعار النص (اختياري):',
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        searchPlaceholder: 'بحث...',
        defaultSourceName: 'محرك بحث جديد'
    },
    'it-IT': {
        settings: 'Impostazioni',
        settingsTitle: 'Impostazioni',
        theme: 'Tema:',
        toggleTheme: '',
        language: 'Lingua:',
        searchSources: 'Fonti di ricerca',
        addSource: 'Aggiungi fonte',
        editSourceTitle: 'Modifica fonte di ricerca',
        sourceName: 'Nome:',
        sourceUrl: 'URL (usa %s per la query):',
        sourceFavicon: 'URL Favicon:',
        sourceLogo: 'Percorso logo testuale (opzionale):',
        save: 'Salva',
        cancel: 'Annulla',
        delete: 'Elimina',
        edit: 'Modifica',
        searchPlaceholder: 'Cerca...',
        defaultSourceName: 'Nuovo motore di ricerca'
    },
    'pt-PT': {
        settings: 'Configurações',
        settingsTitle: 'Configurações',
        theme: 'Tema:',
        toggleTheme: '',
        language: 'Idioma:',
        searchSources: 'Fontes de pesquisa',
        addSource: 'Adicionar fonte',
        editSourceTitle: 'Editar fonte de pesquisa',
        sourceName: 'Nome:',
        sourceUrl: 'URL (use %s para a pesquisa):',
        sourceFavicon: 'URL do Favicon:',
        sourceLogo: 'Caminho do logo de texto (opcional):',
        save: 'Guardar',
        cancel: 'Cancelar',
        delete: 'Eliminar',
        edit: 'Editar',
        searchPlaceholder: 'Pesquisar...',
        defaultSourceName: 'Novo motor de pesquisa'
    },
    'ja-JP': {
        settings: '設定',
        settingsTitle: '設定',
        theme: 'テーマ:',
        toggleTheme: '',
        language: '言語:',
        searchSources: '検索ソース',
        addSource: '新しいソースを追加',
        editSourceTitle: '検索ソースを編集',
        sourceName: '名前:',
        sourceUrl: 'URL (クエリには%sを使用):',
        sourceFavicon: 'ファビコンURL:',
        sourceLogo: 'テキストロゴパス (オプション):',
        save: '保存',
        cancel: 'キャンセル',
        delete: '削除',
        edit: '編集',
        searchPlaceholder: '検索...',
        defaultSourceName: '新しい検索エンジン'
    },
    'de-DE': {
        settings: 'Einstellungen',
        settingsTitle: 'Einstellungen',
        theme: 'Thema:',
        toggleTheme: '',
        language: 'Sprache:',
        searchSources: 'Suchquellen',
        addSource: 'Neue Quelle hinzufügen',
        editSourceTitle: 'Suchquelle bearbeiten',
        sourceName: 'Name:',
        sourceUrl: 'URL (verwenden Sie %s für die Abfrage):',
        sourceFavicon: 'Favicon-URL:',
        sourceLogo: 'Textlogo-Pfad (optional):',
        save: 'Speichern',
        cancel: 'Abbrechen',
        delete: 'Löschen',
        edit: 'Bearbeiten',
        searchPlaceholder: 'Suchen...',
        defaultSourceName: 'Neue Suchmaschine'
    },
    'ko-KR': {
        settings: '설정',
        settingsTitle: '설정',
        theme: '테마:',
        toggleTheme: '',
        language: '언어:',
        searchSources: '검색 소스',
        addSource: '새 소스 추가',
        editSourceTitle: '검색 소스 편집',
        sourceName: '이름:',
        sourceUrl: 'URL (쿼리에는 %s 사용):',
        sourceFavicon: '파비콘 URL:',
        sourceLogo: '텍스트 로고 경로 (선택사항):',
        save: '저장',
        cancel: '취소',
        delete: '삭제',
        edit: '편집',
        searchPlaceholder: '검색...',
        defaultSourceName: '새 검색 엔진'
    },
    'nl-NL': {
        settings: 'Instellingen',
        settingsTitle: 'Instellingen',
        theme: 'Thema:',
        toggleTheme: '',
        language: 'Taal:',
        searchSources: 'Zoekbronnen',
        addSource: 'Nieuwe bron toevoegen',
        editSourceTitle: 'Zoekbron bewerken',
        sourceName: 'Naam:',
        sourceUrl: 'URL (gebruik %s voor zoekopdracht):',
        sourceFavicon: 'Favicon URL:',
        sourceLogo: 'Tekstlogo pad (optioneel):',
        save: 'Opslaan',
        cancel: 'Annuleren',
        delete: 'Verwijderen',
        edit: 'Bewerken',
        searchPlaceholder: 'Zoeken...',
        defaultSourceName: 'Nieuwe zoekmachine'
    },
    'tr-TR': {
        settings: 'Ayarlar',
        settingsTitle: 'Ayarlar',
        theme: 'Tema:',
        toggleTheme: '',
        language: 'Dil:',
        searchSources: 'Arama Kaynakları',
        addSource: 'Yeni Kaynak Ekle',
        editSourceTitle: 'Arama Kaynağını Düzenle',
        sourceName: 'Ad:',
        sourceUrl: 'URL (sorgu için %s kullanın):',
        sourceFavicon: 'Favicon URL:',
        sourceLogo: 'Metin Logosu Yolu (isteğe bağlı):',
        save: 'Kaydet',
        cancel: 'İptal',
        delete: 'Sil',
        edit: 'Düzenle',
        searchPlaceholder: 'Ara...',
        defaultSourceName: 'Yeni Arama Motoru'
    },
    'hi-IN': {
        settings: 'सेटिंग्स',
        settingsTitle: 'सेटिंग्स',
        theme: 'थीम:',
        toggleTheme: '',
        language: 'भाषा:',
        searchSources: 'खोज स्रोत',
        addSource: 'नया स्रोत जोड़ें',
        editSourceTitle: 'खोज स्रोत संपादित करें',
        sourceName: 'नाम:',
        sourceUrl: 'URL (क्वेरी के लिए %s का उपयोग करें):',
        sourceFavicon: 'फेविकॉन URL:',
        sourceLogo: 'टेक्स्ट लोगो पथ (वैकल्पिक):',
        save: 'सहेजें',
        cancel: 'रद्द करें',
        delete: 'हटाएं',
        edit: 'संपादित करें',
        searchPlaceholder: 'खोजें...',
        defaultSourceName: 'नया खोज इंजन'
    },
    'th-TH': {
        settings: 'การตั้งค่า',
        settingsTitle: 'การตั้งค่า',
        theme: 'ธีม:',
        toggleTheme: '',
        language: 'ภาษา:',
        searchSources: 'แหล่งค้นหา',
        addSource: 'เพิ่มแหล่งใหม่',
        editSourceTitle: 'แก้ไขแหล่งค้นหา',
        sourceName: 'ชื่อ:',
        sourceUrl: 'URL (ใช้ %s สำหรับคำค้นหา):',
        sourceFavicon: 'URL ไอคอน:',
        sourceLogo: 'ที่ตั้งโลโก้ (ไม่จำเป็น):',
        save: 'บันทึก',
        cancel: 'ยกเลิก',
        delete: 'ลบ',
        edit: 'แก้ไข',
        searchPlaceholder: 'ค้นหา...',
        defaultSourceName: 'เครื่องมือค้นหาใหม่'
    },
    'vi-VN': {
        settings: 'Cài đặt',
        settingsTitle: 'Cài đặt',
        theme: 'Chủ đề:',
        toggleTheme: '',
        language: 'Ngôn ngữ:',
        searchSources: 'Nguồn tìm kiếm',
        addSource: 'Thêm nguồn mới',
        editSourceTitle: 'Chỉnh sửa nguồn tìm kiếm',
        sourceName: 'Tên:',
        sourceUrl: 'URL (sử dụng %s cho truy vấn):',
        sourceFavicon: 'URL Favicon:',
        sourceLogo: 'Đường dẫn logo (tùy chọn):',
        save: 'Lưu',
        cancel: 'Hủy',
        delete: 'Xóa',
        edit: 'Sửa',
        searchPlaceholder: 'Tìm kiếm...',
        defaultSourceName: 'Công cụ tìm kiếm mới'
    },
    'id-ID': {
        settings: 'Pengaturan',
        settingsTitle: 'Pengaturan',
        theme: 'Tema:',
        toggleTheme: '',
        language: 'Bahasa:',
        searchSources: 'Sumber Pencarian',
        addSource: 'Tambahkan Sumber Baru',
        editSourceTitle: 'Edit Sumber Pencarian',
        sourceName: 'Nama:',
        sourceUrl: 'URL (gunakan %s untuk kueri):',
        sourceFavicon: 'URL Favicon:',
        sourceLogo: 'Path Logo Teks (opsional):',
        save: 'Simpan',
        cancel: 'Batal',
        delete: 'Hapus',
        edit: 'Edit',
        searchPlaceholder: 'Cari...',
        defaultSourceName: 'Mesin Pencari Baru'
    }
};

let currentLanguage = 'en-US'; // Default language

function setLanguage(lang) {
    if (translations[lang]) {
        currentLanguage = lang;
        localStorage.setItem('userLanguage', lang);
        applyTranslations();
    } else {
        console.warn(`Language ${lang} not found. Using default.`);
        currentLanguage = 'en-US';
        applyTranslations();
    }
}

function translate(key) {
    return translations[currentLanguage][key] || translations['en-US'][key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        element.textContent = translate(key);
    });
    document.querySelectorAll('[data-translate-placeholder]').forEach(element => {
        const key = element.getAttribute('data-translate-placeholder');
        element.setAttribute('placeholder', translate(key));
    });
    // Potentially update other dynamic content if needed
}

function getInitialLanguage() {
    return localStorage.getItem('userLanguage') || 'en-US';
}
